_format_version: "3.0"
_transform: true

services:
  - name: pedidos
    url: ${ORDERS_SERVICE_URL}
    routes:
      - name: api-pedidos
        protocols:
          - http
          - https
        paths:
          - /pedidos

  - name: notasFiscais
    url: http://host.docker.internal:3334
    routes:
      - name: api-notasFiscais
        protocols:
          - http
          - https
        paths:
          - /notasFiscais

plugins:
  - name: cors
    config:
      origins:
        - "*"
      methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      headers:
        - Accept
        - Content-Type
        - Authorization
